### ISSUE TITLE
Request error: AxiosError: timeout of 5000ms exceeded

### ISSUE THREAD

**Issue by ahnungsbefreit** [simatec/ioBroker.uv-protect#102]
**Describe the bug**  
The adapter is not able to collect data on a regular basis as per CRON due to timeouts (not always, but frequently), resulting in the following log entry: 

`Request error: AxiosError: timeout of 5000ms exceeded`

**To Reproduce**  
Configure the adapter with proper Token and the following CRON: */30 5-22 * * *

**Versions:**  
 - Adapter version: 0.3.6
 - JS-Controller version: v16.16.0
 - Node version: v16.16.0
 - Operating system: Debian on Proxmox

**Additional context**

**Comment by simatec** [comment]
Unfortunately, the API is not available from time to time. Surely too many requests ... There is nothing the adapter can do ...
