### ISSUE TITLE
Nach js-controller Update auf 5.0.3 "already running"

### ISSUE THREAD

**Issue by m-s-b** [simatec/ioBroker.uv-protect#160]
**Describe the bug**  
Nach Update des js-controllers auf 5.0.3 wird nach dem Abruf der Daten vermutlich nicht richtig beendet.
Bei jedem Abruf erfolgt im LOG die Warnmeldung:
`instance system.adapter.uv-protect.0 already running with pid 1769`
Als Quelle gibt das Log den host.iobroker und nicht den Adapter an.

**Expected behavior**  
Pid 1769 sollte nach dem Abruf gekillt werden.

**Versions:**  
 - Adapter version: 0.4.0
 - JS-Controller version: 5.0.3
 - Node version: <node-version> v18.16.0
 - Operating system: Debian 11

**Comment by simatec** [comment]
Du musst den Pid einmal richtig beenden. Am einfachsten mit einem Neustart des Systems

**Comment by m-s-b** [comment]
Das hatte ich schon gemacht und die Meldung kommt weiterhin.

**Comment by simatec** [comment]
Bitte teste die v0.4.1... Ggfs. nach dem Update noch einmal das System komplett neustarten, damit auch alles sauber beendet wird.

**Comment by m-s-b** [comment]
Danke! Mit 0.4.1 hat er nach reboot jetzt 4 Durchläufe ohne Meldungen geschafft (kurz vor deiner Antwort noch den js-controller 5.0.5 installiert).
