### ISSUE TITLE
Bug: wrong data? / Feature request - UV-Index

### ISSUE THREAD

**Issue by Haifeif** [simatec/ioBroker.uv-protect#183]
Hi there!

Thank you for the great work - giving us a UV instrument at hand! Diving deeper into the sience of UV radiation, I saw that the UV index is something more "easy to handle" for human beeings. 

openuv.io offers this information, but the adapter does not. 

So - that is my feature request

I looked into the math behind UV, and found the formular 

UV-Index = power / 25 

power is measured in W / m²

But the adapter shows (f.e.) 0,8 mW/m² - That means the uV Index in Mülheim / Ruhr, Germany is 0,000032.  That doesn't make sense. So either my formular is wrong, or the data / the adapter is giving me wrong measurements or calculations!

The adapter version is 0.4.2,
Node.js: v18.17.1 
NPM: 9.6.7

Kind Regards, Uwe

**Comment by simatec** [comment]
I don't really understand your issue.
The adapter directly processes the data from the API and does not change anything...
The API outputs the following. What do you need exactly?

`{"result":{"uv":0,"uv_time":"2023-09-23T21:38:02.706Z","uv_max":2.9872,"uv_max_time":"2023-09-23T11:08:10.117Z","ozone":333,"ozone_time":"2023-04-12T15:04:31.773Z","safe_exposure_time":{"st1":null,"st2":null,"st3":null,"st4":null,"st5":null,"st6":null},"sun_info":{"sun_times":{"solarNoon":"2023-09-23T11:08:10.117Z","nadir":"2023-09-22T23:08:10.117Z","sunrise":"2023-09-23T05:02:16.762Z","sunset":"2023-09-23T17:14:03.473Z","sunriseEnd":"2023-09-23T05:05:45.404Z","sunsetStart":"2023-09-23T17:10:34.831Z","dawn":"2023-09-23T04:28:26.796Z","dusk":"2023-09-23T17:47:53.438Z","nauticalDawn":"2023-09-23T03:48:24.242Z","nauticalDusk":"2023-09-23T18:27:55.993Z","nightEnd":"2023-09-23T03:06:35.596Z","night":"2023-09-23T19:09:44.638Z","goldenHourEnd":"2023-09-23T05:46:58.045Z","goldenHour":"2023-09-23T16:29:22.190Z"},"sun_position":{"azimuth":2.6627528913133425,"altitude":-0.6047170162933537}}}} `

**Comment by Haifeif** [comment]
I try to use the UV-Index. But the adapter gives me uv_max as mW/m² - not the dimesion free value of the UV-Index. 

Let me guess something: The uv_max IS UV-Index, only the mW/m² is wrong? That makes sense, looking at the API data. So, maybe nothing is wrong - except the mW/m² ??

Kind Regards, Uwe

**Comment by Haifeif** [comment]
btw - same story with uv 
![image](https://github.com/simatec/ioBroker.uv-protect/assets/59795191/14cdd2b7-2d23-41a8-9e1a-95048e25ed2b)

**Comment by simatec** [comment]
I still don't understand your issue, unfortunately.
The values come directly from the API. If the values are not correct in your opinion, then you should please open an issue there.

Or is it about a wrong unit?

**Comment by Haifeif** [comment]
Hi there. 

 

It is a communication problem:

 

Iwas looking for the UV index. Physicaly this is a number without any extension. 

Your adapter delivers the correct number, but call them mW/m². And that is wrong! The index has no extension! 

And this lead me in the wrong direction – because I tried to calculate a UV index out of numbers. 

 

To fix that issue, just remove the mW/m²! 

 

Regards, Uwe

 

PS: It would be easier for me to explain the problem, if English would be my mother language,  but it isn’t (obviously)

 

Von: simatec ***@***.***> 
Gesendet: Mittwoch, 4. Oktober 2023 09:02
An: simatec/ioBroker.uv-protect ***@***.***>
Cc: Uwe ***@***.***>; Author ***@***.***>
Betreff: Re: [simatec/ioBroker.uv-protect] Bug: wrong data? / Feature request - UV-Index (Issue #183)

 

I still don't understand your issue, unfortunately.
The values come directly from the API. If the values are not correct in your opinion, then you should please open an issue there.

Or is it about a wrong unit?

**Comment by simatec** [comment]
Fix in v0.5.0

**Comment by Haifeif** [comment]
Thx!
