### ISSUE TITLE
wrong value types (?)

### ISSUE THREAD

**Issue by BramTown** [simatec/ioBroker.uv-protect#50]
it seems there are some wrong value types

`<html>
<body>

uv-protect.0 | 2022-02-08 00:10:01.262 | warn | This object will not be created in future versions. Please report this to the developer.
-- | -- | -- | --
uv-protect.0 | 2022-02-08 00:10:01.262 | warn | Object uv-protect.0.uv_warn is invalid: Default value has to be type "boolean" but received type "string"
uv-protect.0 | 2022-02-08 00:10:01.255 | warn | This object will not be created in future versions. Please report this to the developer.
uv-protect.0 | 2022-02-08 00:10:01.255 | warn | Object uv-protect.0.uv_alert is invalid: Default value has to be type "boolean" but received type "string"
uv-protect.0 | 2022-02-08 00:10:01.233 | warn | This object will not be created in future versions. Please report this to the developer.
uv-protect.0 | 2022-02-08 00:10:01.232 | warn | Object uv-protect.0.sun_info.sun_position.altitude is invalid: Default value has to be type "number" but received type "string"
uv-protect.0 | 2022-02-08 00:10:01.183 | warn | This object will not be created in future versions. Please report this to the developer.
uv-protect.0 | 2022-02-08 00:10:01.183 | warn | Object uv-protect.0.sun_info.sun_position.azimuth is invalid: Default value has to be type "number" but received type "string"
uv-protect.0 | 2022-02-08 00:10:01.114 | warn | This object will not be created in future versions. Please report this to the developer.
uv-protect.0 | 2022-02-08 00:10:01.114 | warn | Object uv-protect.0.safe_exposure_time.st6 is invalid: Default value has to be type "number" but received type "string"
uv-protect.0 | 2022-02-08 00:10:01.103 | warn | This object will not be created in future versions. Please report this to the developer.
uv-protect.0 | 2022-02-08 00:10:01.102 | warn | Object uv-protect.0.safe_exposure_time.st5 is invalid: Default value has to be type "number" but received type "string"
uv-protect.0 | 2022-02-08 00:10:01.094 | warn | This object will not be created in future versions. Please report this to the developer.
uv-protect.0 | 2022-02-08 00:10:01.093 | warn | Object uv-protect.0.safe_exposure_time.st4 is invalid: Default value has to be type "number" but received type "string"
uv-protect.0 | 2022-02-08 00:10:01.081 | warn | This object will not be created in future versions. Please report this to the developer.
uv-protect.0 | 2022-02-08 00:10:01.081 | warn | Object uv-protect.0.safe_exposure_time.st3 is invalid: Default value has to be type "number" but received type "string"
uv-protect.0 | 2022-02-08 00:10:01.072 | warn | This object will not be created in future versions. Please report this to the developer.
uv-protect.0 | 2022-02-08 00:10:01.069 | warn | Object uv-protect.0.safe_exposure_time.st2 is invalid: Default value has to be type "number" but received type "string"
uv-protect.0 | 2022-02-08 00:10:01.060 | warn | This object will not be created in future versions. Please report this to the developer.
uv-protect.0 | 2022-02-08 00:10:01.059 | warn | Object uv-protect.0.safe_exposure_time.st1 is invalid: Default value has to be type "number" but received type "string"
uv-protect.0 | 2022-02-08 00:10:01.045 | warn | This object will not be created in future versions. Please report this to the developer.
uv-protect.0 | 2022-02-08 00:10:01.041 | warn | Object uv-protect.0.ozone is invalid: Default value has to be type "number" but received type "string"
uv-protect.0 | 2022-02-08 00:10:01.023 | warn | This object will not be created in future versions. Please report this to the developer.
uv-protect.0 | 2022-02-08 00:10:01.022 | warn | Object uv-protect.0.uv_max is invalid: Default value has to be type "number" but received type "string"
uv-protect.0 | 2022-02-08 00:10:01.001 | warn | This object will not be created in future versions. Please report this to the developer.
uv-protect.0 | 2022-02-08 00:10:00.999 | warn | Object uv-protect.0.uv is invalid: Default value has to be type "number" but received type "string"
uv-protect.0 | 2022-02-08 00:08:37.958 | warn | This object will not be created in future versions. Please report this to the developer.
uv-protect.0 | 2022-02-08 00:08:37.957 | warn | Object uv-protect.0.uv_warn is invalid: Default value has to be type "boolean" but received type "string"
uv-protect.0 | 2022-02-08 00:08:37.949 | warn | This object will not be created in future versions. Please report this to the developer.
uv-protect.0 | 2022-02-08 00:08:37.949 | warn | Object uv-protect.0.uv_alert is invalid: Default value has to be type "boolean" but received type "string"
uv-protect.0 | 2022-02-08 00:08:37.925 | warn | This object will not be created in future versions. Please report this to the developer.
uv-protect.0 | 2022-02-08 00:08:37.924 | warn | Object uv-protect.0.sun_info.sun_position.altitude is invalid: Default value has to be type "number" but received type "string"
uv-protect.0 | 2022-02-08 00:08:37.873 | warn | This object will not be created in future versions. Please report this to the developer.
uv-protect.0 | 2022-02-08 00:08:37.873 | warn | Object uv-protect.0.sun_info.sun_position.azimuth is invalid: Default value has to be type "number" but received type "string"
uv-protect.0 | 2022-02-08 00:08:37.790 | warn | This object will not be created in future versions. Please report this to the developer.
uv-protect.0 | 2022-02-08 00:08:37.789 | warn | Object uv-protect.0.safe_exposure_time.st6 is invalid: Default value has to be type "number" but received type "string"
uv-protect.0 | 2022-02-08 00:08:37.777 | warn | This object will not be created in future versions. Please report this to the developer.
uv-protect.0 | 2022-02-08 00:08:37.776 | warn | Object uv-protect.0.safe_exposure_time.st5 is invalid: Default value has to be type "number" but received type "string"
uv-protect.0 | 2022-02-08 00:08:37.759 | warn | This object will not be created in future versions. Please report this to the developer.
uv-protect.0 | 2022-02-08 00:08:37.758 | warn | Object uv-protect.0.safe_exposure_time.st4 is invalid: Default value has to be type "number" but received type "string"
uv-protect.0 | 2022-02-08 00:08:37.743 | warn | This object will not be created in future versions. Please report this to the developer.
uv-protect.0 | 2022-02-08 00:08:37.743 | warn | Object uv-protect.0.safe_exposure_time.st3 is invalid: Default value has to be type "number" but received type "string"
uv-protect.0 | 2022-02-08 00:08:37.729 | warn | This object will not be created in future versions. Please report this to the developer.
uv-protect.0 | 2022-02-08 00:08:37.728 | warn | Object uv-protect.0.safe_exposure_time.st2 is invalid: Default value has to be type "number" but received type "string"
uv-protect.0 | 2022-02-08 00:08:37.680 | warn | This object will not be created in future versions. Please report this to the developer.
uv-protect.0 | 2022-02-08 00:08:37.679 | warn | Object uv-protect.0.safe_exposure_time.st1 is invalid: Default value has to be type "number" but received type "string"
uv-protect.0 | 2022-02-08 00:08:37.663 | warn | This object will not be created in future versions. Please report this to the developer.
uv-protect.0 | 2022-02-08 00:08:37.662 | warn | Object uv-protect.0.ozone is invalid: Default value has to be type "number" but received type "string"
uv-protect.0 | 2022-02-08 00:08:37.606 | warn | This object will not be created in future versions. Please report this to the developer.
uv-protect.0 | 2022-02-08 00:08:37.606 | warn | Object uv-protect.0.uv_max is invalid: Default value has to be type "number" but received type "string"
uv-protect.0 | 2022-02-08 00:08:37.584 | warn | This object will not be created in future versions. Please report this to the developer.
uv-protect.0 | 2022-02-08 00:08:37.582 | warn | Object uv-protect.0.uv is invalid: Default value has to be type "number" but received type "string"

</body>
</html>`

**Comment by simatec** [comment]
Fix with Version 0.3.5
